setGeneric("psms", function(object, ...) standardGeneric("psms"))
setGeneric("peaks", function(object, ...) standardGeneric("peaks"))
setGeneric("peaks<-", function(object, ..., value) standardGeneric("peaks<-"))
setGeneric("modifications", function(object, ...) standardGeneric("modifications"))
setGeneric("database", function(object, ...) standardGeneric("database"))
setGeneric("rtime", function(object, ...) standardGeneric("rtime")) 
setGeneric("tic", function(object, ...) standardGeneric("tic"))

setGeneric("spectra", function(object, ...) standardGeneric("spectra"))
setGeneric("spectra<-", function(object, ..., value) standardGeneric("spectra<-"))

setGeneric("ionCount", function(object, ...) standardGeneric("ionCount"))
setGeneric("scanIndex", function(object) standardGeneric("scanIndex"))
setGeneric("precursorMz", function(object) standardGeneric("precursorMz"))
setGeneric("precursorIntensity", function(object) standardGeneric("precursorIntensity"))
setGeneric("precursorCharge", function(object) standardGeneric("precursorCharge"))
setGeneric("precursorCharge<-", function(object, value) standardGeneric("precursorCharge<-"))
setGeneric("acquisitionNum", function(object) standardGeneric("acquisitionNum"))
setGeneric("precAcquisitionNum", function(object) standardGeneric("precAcquisitionNum"))
setGeneric("precScanNum", function(object) standardGeneric("precScanNum"))
setGeneric("msLevel", function(object) standardGeneric("msLevel"))
setGeneric("collisionEnergy", function(object) standardGeneric("collisionEnergy"))
setGeneric("polarity", function(object) standardGeneric("polarity"))
setGeneric("intensity", function(object, ...) standardGeneric("intensity"))
setGeneric("mz", function(object, ...) standardGeneric("mz"))

setGeneric("processingData", function(object) standardGeneric("processingData"))
setGeneric("processingData<-", function(object, value) standardGeneric("processingData<-"))

setGeneric("msInfo", function(object) standardGeneric("msInfo"))
setGeneric("expemail", function(object) standardGeneric("expemail"))
setGeneric("exptitle", function(object) standardGeneric("exptitle"))
setGeneric("ionSource", function(object) standardGeneric("ionSource"))
setGeneric("ionSourceDetails", function(object) standardGeneric("ionSourceDetails"))
setGeneric("analyser", function(object) standardGeneric("analyser"))
setGeneric("analyzer", function(object) standardGeneric("analyzer"))
setGeneric("analyzerDetails", function(object) standardGeneric("analyzerDetails"))
setGeneric("analyserDetails", function(object) standardGeneric("analyserDetails"))
setGeneric("detectorType", function(object) standardGeneric("detectorType"))
setGeneric("instrumentManufacturer", function(object) standardGeneric("instrumentManufacturer"))
setGeneric("instrumentCustomisations", function(object) standardGeneric("instrumentCustomisations"))

## stats::smooth already exists
setGeneric("smooth", function(x, ...) standardGeneric("smooth"))
setGeneric("centroided", function(object, ...) standardGeneric("centroided"))
setGeneric("centroided<-", function(object, ..., value) standardGeneric("centroided<-"))
setGeneric("smoothed", function(object) standardGeneric("smoothed"))
setGeneric("smoothed<-", function(object, ..., value) standardGeneric("smoothed<-"))
setGeneric("instrumentModel", function(object) standardGeneric("instrumentModel"))

setGeneric("peptides", function(object, ...) standardGeneric("peptides"))
setGeneric("proteins", function(object, ...) standardGeneric("proteins"))
setGeneric("accessions", function(object, ...) standardGeneric("accessions"))
setGeneric("scans", function(object, ...) standardGeneric("scans"))
setGeneric("mass", function(object, ...) standardGeneric("mass"))
setGeneric("ions", function(object, ...) standardGeneric("ions"))
setGeneric("chromatograms", function(object, ...) standardGeneric("chromatograms"))
setGeneric("chromatogram", function(object, ...) standardGeneric("chromatogram"))
setGeneric("mz<-", function(object, value) standardGeneric("mz<-"))
setGeneric("isCentroided", function(object, ...) standardGeneric("isCentroided"))

setGeneric("writeMSData", function(object, file, ...) standardGeneric("writeMSData"))


